### ISSUE TITLE
スタイル崩れ

### ISSUE THREAD

**Issue by N-Magi** [kirue129/portfolio#12]
環境:Edge
内容:文字が読めない
https://gyazo.com/4214b5dbcd662c58ac83cf0d5627adc5

**Comment by kirue129** [comment]
上司の目を盗みながら勧めてたけど、バレた（多分）なので途中でマージしちった（テヘ）
ちゃんとprたててなおすのでゆるしちくり

**Comment by kirue129** [comment]
内容的にはまだ #10 の途中なので以降はこっちで
なので閉じまする
